name: Prettier
on:
  pull_request:
    branches: [master]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 17
      - name: Install dependiences
      - run: npm install
      - name: Check formatting with Prettier
        run: npm prettier:check
